#!/usr/bin/env sh

set -e

if ! command -v yarn > /dev/null; then
  npm install --global yarn
fi
yarn install

if ! command -v bundler > /dev/null; then
  gem install bundler:2.1.4
fi

bundle check || bundle install
