#!/usr/bin/env bash

set -e

PROJECT_ROOT=$(dirname "${BASH_SOURCE[0]}")/../

if ! command -v yarn > /dev/null; then
  npm install --global yarn
fi

cd $PROJECT_ROOT

yarn install

cd -

gem install bundler --conservative

bundle check || bundle install --jobs 4 --retry 3 --gemfile="$PROJECT_ROOT/Gemfile"
