#!/usr/bin/env sh

set -e

SHA=$1

export LANG=C
export GIT_SHA=${SHA}
export GIT_SUBJECT="$(git show --no-patch --format='%s' $SHA | sed -e 's/\"/\\"/g')"
export GIT_MESSAGE="$(git show --no-patch --format='%b' $SHA | sed -e 's/^/  /g')"
export GIT_DIFF="$(git show --cc --format='' $SHA | sed -e 's/^/  /g')"

envsubst < templates/data/commit.yml.tmpl
