name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.6.6"
        bundler-cache: true
    - uses: actions/setup-node@v2
      with:
        node-version: "12.x"

    - run: |
        git config --global user.email "ci@example.com"
        git config --global user.name "GitHub Actions"

        bundle install --jobs 4 --retry 3
        yarn install

    - run: bundle exec rake
