name: git-read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.6.6"
        bundler-cache: true

    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Build documentation from Git History
      run: |
        script/install
        bin/git-read --git-dir ./ --build-dir ./build --path-prefix "/$(basename $GITHUB_REPOSITORY)"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        commit_message: ${{ github.event.head_commit.message }}
        publish_dir: ./build
