name: git-read

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
        path: vendor/bundle
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.6.5"
        run: bundle config path vendor/bundle
    - name: Fetch full Git History and build documentation
      run: |
        git fetch --prune --unshallow
        bin/git-read --git-dir ./ --build-dir ./build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        commit_message: ${{ github.event.head_commit.message }}
        publish_dir: ./build
