name: git-read

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch full Git History
      run: |
        git fetch --prune --unshallow
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.6.5"
    - name: Build documentation
      run: |
        make install
        make
      env:
        BUNDLE_PATH: vendor/bundle
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        commit_message: ${{ github.event.head_commit.message }}
        publish_dir: ./build
