name: git-read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-ruby@v1.1.1
        with:
          ruby-version: "2.6.x"

      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
          path: vendor/bundle

      - name: Build documentation from Git History
        env:
          BUNDLE_PATH: vendor/bundle
        run: |
          script/install
          bin/git-read --git-dir ./ --build-dir ./build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
          publish_dir: ./build
